version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: possum_mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: possum_db
      MYSQL_USER: possum_user
      MYSQL_PASSWORD: possum_pass

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: